name: Frontend Lint & Build

on:
  push:
    paths:
      - 'client/**'
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
